name: CI

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Runs a single command using the runners shell
      - run: |
          if [ "${{ startsWith(github.ref, 'refs/tags') }}" = "true" ]; then
            BUILD_REF=${{ github.ref }}
            make push TAG="${BUILD_REF/refs\/tags\//}"
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            make push TAG="pr-${{ github.event.number }}"
          else
            make push TAG="${{ github.sha }}"
          fi
